import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://52.170.147.30/auth/signup');
  await page.getByPlaceholder('Type your password', { exact: true }).click();
  await page.getByPlaceholder('Type your password', { exact: true }).fill('Abc123@Ab123@');
  await page.locator('i').getByRole('img').click();
  await page.getByPlaceholder('Type your password again').click();
  await page.getByPlaceholder('Type your password again').fill('Abc123@Ab123@');
  await page.locator('div').filter({ hasText: /^Confirm Password$/ }).getByRole('img').click();
  await page.goto('http://52.170.147.30/auth/signup');
  await page.getByPlaceholder('Type your email address').click();
  await page.getByPlaceholder('Type your email address').fill('Abc123@123.com');
  await page.goto('http://52.170.147.30/auth/signup');
  await page.getByPlaceholder('Type your email address').click();
  await page.getByPlaceholder('Type your email address').fill('123.com');
  await page.getByPlaceholder('Type your password', { exact: true }).click();
  await page.getByText('Invalid format for Email!').click();
  await page.goto('http://52.170.147.30/auth/signup');
  await page.getByPlaceholder('Type your email address').click();
  await page.getByPlaceholder('Type your email address').fill('Abc123@123.com');
  await page.getByPlaceholder('Type your password', { exact: true }).click();
  await page.getByPlaceholder('Type your password', { exact: true }).click();
  await page.getByPlaceholder('Type your password', { exact: true }).fill('Ab123@Ab123@');
  await page.getByPlaceholder('Type your password again').click();
  await page.getByPlaceholder('Type your password again').fill('Ab123@Ab123@Ab123@');
  await page.locator('div').filter({ hasText: /^Password$/ }).getByRole('img').click();
  await page.locator('div').filter({ hasText: /^Confirm Password$/ }).getByRole('img').click();
  await page.getByRole('button', { name: 'Sign Up' }).click();
  await page.getByRole('heading', { name: 'Password and Confirm password' }).click();
  await page.goto('http://52.170.147.30/auth/signup');
  await page.getByPlaceholder('Type your email address').click();
  await page.getByPlaceholder('Type your password', { exact: true }).click();
  await page.getByText('Email is required!').click();
  await page.getByText('Password is required!').click();
  await page.getByPlaceholder('Type your password again').click();
  await page.getByPlaceholder('Type your password', { exact: true }).click();
  await page.getByText('Repeat Password is required!').click();
  await page.getByText('Email', { exact: true }).click();
  await page.goto('http://52.170.147.30/auth/signup');
  await page.getByPlaceholder('Type your email address').click();
  await page.getByPlaceholder('Type your email address').fill('suleyman.atmaca@emm-it.de');
  await page.getByPlaceholder('Type your password', { exact: true }).click();
  await page.getByPlaceholder('Type your password', { exact: true }).fill('T%633642945806oc');
  await page.getByPlaceholder('Type your password again').click();
  await page.getByPlaceholder('Type your password again').fill('T%633642945806oc');
  await page.locator('div').filter({ hasText: /^Confirm Password$/ }).getByRole('img').click();
  await page.locator('div').filter({ hasText: /^Password$/ }).getByRole('img').click();
  await page.getByRole('button', { name: 'Sign Up' }).click();
  await page.getByRole('heading', { name: 'We\'re experiencing technical' }).click();
  await page.getByRole('heading', { name: 'We\'re experiencing technical' }).click();
  await page.goto('http://52.170.147.30/auth/signup');
  await page.getByPlaceholder('Type your email address').click();
  await page.getByPlaceholder('Type your email address').fill('Abc123@123.com');
  await page.getByPlaceholder('Type your password', { exact: true }).click();
  await page.getByPlaceholder('Type your password', { exact: true }).fill('Ab123@');
  await page.getByPlaceholder('Type your password again').click();
  await page.getByText('Password must be between 8').click();
  await page.getByPlaceholder('Type your password again').click();
  await page.getByPlaceholder('Type your password again').fill('Ab123@');
  await page.getByPlaceholder('Type your password', { exact: true }).click();
  await page.getByPlaceholder('Type your email address').click();
  await page.getByPlaceholder('Type your email address').fill('Abc123@123.com');
  await page.getByPlaceholder('Type your password', { exact: true }).click();
  await page.getByPlaceholder('Type your password', { exact: true }).fill('B123@B123@');
  await page.getByPlaceholder('Type your password again').click();
  await page.getByText('Password must include at').click();
  await page.getByPlaceholder('Type your email address').click();
  await page.getByPlaceholder('Type your email address').fill('Abc123@123.com');
  await page.getByPlaceholder('Type your password', { exact: true }).click();
  await page.getByPlaceholder('Type your password', { exact: true }).fill('b123@b123@');
  await page.getByPlaceholder('Type your password again').click();
  await page.getByText('Password must include at').click();
  await page.goto('http://52.170.147.30/auth/signup');
  await page.getByText('Already have an account?').click();
  await page.getByRole('heading', { name: 'Sign In' }).click();
  await page.getByText('Not registered yet?').click();
  await page.getByPlaceholder('Type your email address').click();
  await page.getByPlaceholder('Type your email address').fill('Abc123@123.com');
  await page.getByPlaceholder('Type your password', { exact: true }).click();
  await page.getByPlaceholder('Type your password', { exact: true }).fill('Abc123@Abc123@');
  await page.getByPlaceholder('Type your password again').click();
  await page.getByPlaceholder('Type your password again').fill('Abc123@Abc123@');
  await page.getByRole('button', { name: 'Sign Up' }).click();
  await page.getByRole('heading', { name: 'We\'re experiencing technical' }).click();
  await page.getByPlaceholder('Type your email address').click();
  await page.getByPlaceholder('Type your email address').press('ArrowLeft');
  await page.getByPlaceholder('Type your email address').press('ArrowLeft');
  await page.getByPlaceholder('Type your email address').press('ArrowLeft');
  await page.getByPlaceholder('Type your email address').press('ArrowLeft');
  await page.getByPlaceholder('Type your email address').fill('Abc123@456.com');
  await page.getByPlaceholder('Type your email address').click();
  await page.getByPlaceholder('Type your email address').dblclick();
  await page.getByPlaceholder('Type your email address').click();
  await page.getByRole('button', { name: 'Sign Up' }).click();
  await page.getByRole('heading', { name: 'We\'re experiencing technical' }).click();
  await page.goto('http://52.170.147.30/auth/signup');
  await page.getByPlaceholder('Type your email address').click();
  await page.getByPlaceholder('Type your password', { exact: true }).click();
  await page.getByPlaceholder('Type your password again').click();
  await page.getByText('Course ManagerSign').click();
});